# Generated by Django 5.2.8 on 2025-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_login',
            field=models.BooleanField(default=False),
        ),
    ]
