# Generated by Django 5.2.8 on 2026-01-01 16:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('booking_date', models.DateField()),
                ('guest_name', models.CharField(max_length=200)),
                ('room_no', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_type', models.CharField(blank=True, max_length=50, null=True)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('booking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.PositiveSmallIntegerField(choices=[(0, 'STAFF'), (1, 'WEBSITE')], default=0)),
                ('website_item_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CafeteriaExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaundryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaundryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=255)),
                ('products_used', models.JSONField(default=list, help_text='Example: [{"item_id":1,"item_name": "Bedsheet", "quantity": 10}]')),
                ('description', models.TextField(blank=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('being', models.TextField(blank=True)),
                ('paid_by', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True)),
                ('online_payment_mode', models.CharField(blank=True, help_text='GPay / PhonePe / Paytm / UPI / NetBanking', max_length=100, null=True)),
                ('authorized_by', models.CharField(max_length=200)),
                ('receiver_signature_name', models.CharField(max_length=200)),
                ('receiver_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('products_used', models.JSONField(default=list, help_text='Example: [{"item_id":1,"item_name": "Floor Cleaner", "quantity": 2}]')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_code', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_type', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['date'], name='staff_manag_date_662baa_idx'), models.Index(fields=['source_type', 'source_id'], name='staff_manag_source__52acbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_management.categorymaster')),
            ],
        ),
    ]
