# Generated by Django 5.2.8 on 2025-11-26 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
