# Generated by Django 5.2.8 on 2025-11-28 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0003_otherincome_salesincome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundrylog',
            old_name='quantity_received',
            new_name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='laundrylog',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='laundrylog',
            name='quantity_sent',
        ),
        migrations.RemoveField(
            model_name='laundrylog',
            name='remarks',
        ),
        migrations.AddField(
            model_name='laundrylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundrylog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laundrylog',
            name='products_used',
            field=models.JSONField(default=list, help_text='Example: [{"item_id":1,"item_name": "Bedsheet", "quantity": 10}]'),
        ),
        migrations.AddField(
            model_name='laundrylog',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
