# Generated by Django 5.2.8 on 2025-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0004_rename_quantity_received_laundrylog_received_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('being', models.TextField(blank=True)),
                ('paid_by', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=20)),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True)),
                ('authorized_by', models.CharField(max_length=200)),
                ('receiver_signature', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
