# Generated by Django 5.2.8 on 2025-11-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0005_paymentvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaundryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='expenses/bills/')),
                ('voucher_file', models.FileField(blank=True, null=True, upload_to='expenses/vouchers/')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
