# Generated by Django 5.2.8 on 2025-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0006_cafeteriaexpense_capitalexpense_cleaningexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('guest_name', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=50)),
                ('booking_type', models.CharField(max_length=50)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('booking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BookingTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
