# Generated by Django 5.2.8 on 2025-11-30 14:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0008_booking_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source_type', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['date'], name='staff_manag_date_662baa_idx'), models.Index(fields=['source_type', 'source_id'], name='staff_manag_source__52acbf_idx')],
            },
        ),
    ]
