# Generated by Django 5.2.8 on 2025-12-13 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0010_booking_created_at_booking_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrylog',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryexpense',
            name='staff_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
