# Generated by Django 5.2.8 on 2025-12-14 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0011_laundrylog_company_name_salaryexpense_staff_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='receiver_signature_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='receiver_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
