# Generated by Django 5.2.8 on 2025-12-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0012_paymentvoucher_receiver_signature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='online_payment_mode',
            field=models.CharField(blank=True, help_text='GPay / PhonePe / Paytm / UPI / NetBanking', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='paid_by',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20),
        ),
    ]
