# Generated by Django 5.2.8 on 2025-12-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0013_paymentvoucher_online_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STAFF'), (1, 'WEBSITE')], default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='website_item_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
