# Generated by Django 5.2.8 on 2025-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0014_booking_source_booking_website_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
